server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beauty_co?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: root
